global:
  scrape_interval: 2s     # 로컬 테스트용 고해상도 수집 (기존 5s -> 2s)
  evaluation_interval: 2s

scrape_configs:
  # Spring Boot Actuator 수집
  - job_name: 'pin4u-application'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']

  # Redis Exporter 수집
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']